# Generated by Django 3.0.6 on 2020-05-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cytomine_softwares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docker',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='job',
            name='docker_image',
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cytomine_softwares.Image', verbose_name='Docker Image name'),
            preserve_default=False,
        ),
    ]
