# Generated by Django 3.0.6 on 2020-05-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cytomine_softwares', '0002_auto_20200523_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Docker Image', 'verbose_name_plural': 'Docker Images'},
        ),
    ]
