# Generated by Django 3.0.6 on 2020-05-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cytomine_softwares', '0004_auto_20200524_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joberror',
            name='stdout',
        ),
    ]
