# Generated by Django 3.0.6 on 2020-05-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cytomine_softwares', '0005_remove_joberror_stdout'),
    ]

    operations = [
        migrations.AddField(
            model_name='joberror',
            name='stdout',
            field=models.TextField(blank=True),
        ),
    ]
