# Generated by Django 3.0.6 on 2020-05-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cytomine_softwares', '0006_joberror_stdout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('0', 'Not started'), ('1', 'Completed'), ('2', 'In progress'), ('3', 'Failed'), ('4', 'Needs verification')], default='0', max_length=1),
        ),
    ]
